import React from 'react';

export const genderOption = [
  { key: 'Male', text: 'Male', value: 'Male' },
  { key: 'Female', text: 'Female', value: 'Female' },
]

export const speciesOption = [
  { key: 'Cat', text: 'Cat', value: 'Cat' },
  { key: 'Dog', text: 'Dog', value: 'Dog' },
  { key: 'Rabbit', text: 'Rabbit', value: 'Rabbit' },
  { key: 'Hamster', text: 'Hamster', value: 'Hamster' },
  { key: 'Bird', text: 'Bird', value: 'Bird' },
  { key: 'Guinea Pig', text: 'Guinea Pig', value: 'Guinea Pig' },
]

export const sortOption = [
  { key: "Price: Low to High", text: "Price: Low to High", value: "ascending" },
  { key: "Price: High to Low", text: "Price: High to Low", value: "descending" }
]

export const locationOption = [
  {key: "Alabama", text: "Alabama", value: "Alabama"},
  {key: "Alaska", text: "Alaska", value: "Alaska"},
  {key: "Arizona", text: "Arizona", value: "Arizona"},
  {key: "Arkansas", text: "Arkansas", value: "Arkansas"},
  {key: "California", text: "California", value: "California"},
  {key: "Colorado", text: "Colorado", value: "Colorado"},
  {key: "Connecticut", text: "Connecticut", value: "Connecticut"},
  {key: "Delaware", text: "Delaware", value: "Delaware"},
  {key: "District of Columbia", text: "District of Columbia", value: "District of Columbia"},
  {key: "Florida", text: "Florida", value: "Florida"},
  {key: "Georgia", text: "Georgia", value: "Georgia"},
  {key: "Hawaii", text: "Hawaii", value: "Hawaii"},
  {key: "Idaho", text: "Idaho", value: "Idaho"},
  {key: "Illinois", text: "Illinois", value: "Illinois"},
  {key: "Indiana", text: "Indiana", value: "Indiana"},
  {key: "Iowa", text: "Iowa", value: "Iowa"},
  {key: "Kansas", text: "Kansas", value: "Kansas"},
  {key: "Kentucky", text: "Kentucky", value: "Kentucky"},
  {key: "Louisiana", text: "Louisiana", value: "Louisiana"},
  {key: "Maine", text: "Maine", value: "Maine"},
  {key: "Maryland", text: "Maryland", value: "Maryland"},
  {key: "Massachusetts", text: "Massachusetts", value: "Massachusetts"},
  {key: "Michigan", text: "Michigan", value: "Michigan"},
  {key: "Minnesota", text: "Minnesota", value: "Minnesota"},
  {key: "Mississippi", text: "Mississippi", value: "Mississippi"},
  {key: "Missouri", text: "Missouri", value: "Missouri"},
  {key: "Montana", text: "Montana", value: "Montana"},
  {key: "Nebraska", text: "Nebraska", value: "Nebraska"},
  {key: "Nevada", text: "Nevada", value: "Nevada"},
  {key: "New Hampshire", text: "New Hampshire", value: "New Hampshire"},
  {key: "New Jersey", text: "New Jersey", value: "New Jersey"},
  {key: "New Mexico", text: "New Mexico", value: "New Mexico"},
  {key: "New York", text: "New York", value: "New York"},
  {key: "North Carolina", text: "North Carolina", value: "North Carolina"},
  {key: "North Dakota", text: "North Dakota", value: "North Dakota"},
  {key: "Ohio", text: "Ohio", value: "Ohio"},
  {key: "Oklahoma", text: "Oklahoma", value: "Oklahoma"},
  {key: "Oregon", text: "Oregon", value: "Oregon"},
  {key: "Pennsylvania", text: "Pennsylvania", value: "Pennsylvania"},
  {key: "Rhode Island", text: "Rhode Island", value: "Rhode Island"},
  {key: "South Carolina", text: "South Carolina", value: "South Carolina"},
  {key: "South Dakota", text: "South Dakota", value: "South Dakota"},
  {key: "Tennessee", text: "Tennessee", value: "Tennessee"},
  {key: "Texas", text: "Texas", value: "Texas"},
  {key: "Utah", text: "Utah", value: "Utah"},
  {key: "Vermont", text: "Vermont", value: "Vermont"},
  {key: "Virginia", text: "Virginia", value: "Virginia"},
  {key: "Washington", text: "Washington", value: "Washington"},
  {key: "West Virginia", text: "West Virginia", value: "West Virginia"},
  {key: "Wisconsin", text: "Wisconsin", value: "Wisconsin"},
  {key: "Wyoming", text: "Wyoming", value: "Wyoming"},
]

export const catBreedOption = [
  { key: 'Abyssinian', text: 'Abyssinian', value: 'Abyssinian' },
  { key: 'American Bobtail', text: 'American Bobtail', value: 'American Bobtail' },
  { key: 'American Curl', text: 'American Curl', value: 'American Curl' },
  { key: 'American Shorthair', text: 'American Shorthair', value: 'American Shorthair' },
  { key: 'American Wirehair', text: 'American Wirehair', value: 'American Wirehair' },
  { key: 'Balinese', text: 'Balinese', value: 'Balinese' },
  { key: 'Bengal', text: 'Bengal', value: 'Bengal' },
  { key: 'Birman', text: 'Birman', value: 'Birman' },
  { key: 'Bombay', text: 'Bombay', value: 'Bombay' },
  { key: 'British Shorthair', text: 'British Shorthair', value: 'British Shorthair' },
  { key: 'Burmese', text: 'Burmese', value: 'Burmese' },
  { key: 'Burmilla', text: 'Burmilla', value: 'Burmilla' },
  { key: 'Chartreux', text: 'Chartreux', value: 'Chartreux' },
  { key: 'Colorpoint Shorthair', text: 'Colorpoint Shorthair', value: 'Colorpoint Shorthair' },
  { key: 'Cornish Rex', text: 'Cornish Rex', value: 'Cornish Rex' },
  { key: 'Devon Rex', text: 'Devon Rex', value: 'Devon Rex' },
  { key: 'Domestic Short Hair', text: 'Domestic Short Hair', value: 'Domestic Short Hair' },
  { key: 'Domestic Medium Hair', text: 'Domestic Medium Hair', value: 'Domestic Medium Hair' },
  { key: 'Domestic Long Hair', text: 'Domestic Long Hair', value: 'Domestic Long Hair' },
  { key: 'Egyptian Mau', text: 'Egyptian Mau', value: 'Egyptian Mau' },
  { key: 'European Burmese', text: 'European Burmese', value: 'European Burmese' },
  { key: 'Exotic', text: 'Exotic', value: 'Exotic' },
  { key: 'Havana Brown', text: 'Havana Brown', value: 'Havana Brown' },
  { key: 'Japanese Bobtail', text: 'Japanese Bobtail', value: 'Japanese Bobtail' },
  { key: 'Khao Manee', text: 'Khao Manee', value: 'Khao Manee' },
  { key: 'Korat', text: 'Korat', value: 'Korat' },
  { key: 'LaPerm', text: 'LaPerm', value: 'LaPerm' },
  { key: 'Lykoi', text: 'Lykoi', value: 'Lykoi' },
  { key: 'Maine Coon Cat', text: 'Maine Coon Cat', value: 'Maine Coon Cat' },
  { key: 'Manx', text: 'Manx', value: 'Manx' },
  { key: 'Norwegian Forest Cat', text: 'Norwegian Forest Cat', value: 'Norwegian Forest Cat' },
  { key: 'Ocicat', text: 'Ocicat', value: 'Ocicat' },
  { key: 'Oriental', text: 'Oriental', value: 'Oriental' },
  { key: 'Persian', text: 'Persian', value: 'Persian' },
  { key: 'RagaMuffin', text: 'RagaMuffin', value: 'RagaMuffin' },
  { key: 'Ragdoll', text: 'Ragdoll', value: 'Ragdoll' },
  { key: 'Russian Blue', text: 'Russian Blue', value: 'Russian Blue' },
  { key: 'Scottish Fold', text: 'Scottish Fold', value: 'Scottish Fold' },
  { key: 'Selkirk Rex', text: 'Selkirk Rex', value: 'Selkirk Rex' },
  { key: 'Siamese', text: 'Siamese', value: 'Siamese' },
  { key: 'Siberian', text: 'Siberian', value: 'Siberian' },
  { key: 'Singapura', text: 'Singapura', value: 'Singapura' },
  { key: 'Somali', text: 'Somali', value: 'Somali' },
  { key: 'Sphynx', text: 'Sphynx', value: 'Sphynx' },
  { key: 'Tonkinese', text: 'Tonkinese', value: 'Tonkinese' },
  { key: 'Toybob', text: 'Toybob', value: 'Toybob' },
  { key: 'Turkish Angora', text: 'Turkish Angora', value: 'Turkish Angora' },
  { key: 'Turkish Van', text: 'Turkish Van', value: 'Turkish Van' },
]

export const dogBreedOption = [
  {key: "Affenpinscher", text: "Affenpinscher", value: "Affenpinscher"},
  {key: "Afghan Hound", text: "Afghan Hound", value: "Afghan Hound"},
  {key: "Airdale Terrier", text: "Airdale Terrier", value: "Airdale Terrier"},
  {key: "Akita", text: "Akita", value: "Akita"},
  {key: "Alaskan Malamute", text: "Alaskan Malamute", value: "Alaskan Malamute"},
  {key: "American Eskimo", text: "American Eskimo", value: "American Eskimo"},
  {key: "American Foxhound", text: "American Foxhound", value: "American Foxhound"},
  {key: "American Staffordshire Terrier", text: "American Staffordshire Terrier", value: "American Staffordshire Terrier"},
  {key: "American Water Spaniel", text: "American Water Spaniel", value: "American Water Spaniel"},
  {key: "Anatolian Sheepdog", text: "Anatolian Sheepdog", value: "Anatolian Sheepdog"},
  {key: "Australian Cattle Dog", text: "Australian Cattle Dog", value: "Australian Cattle Dog"},
  {key: "Australian Shepherd", text: "Australian Shepherd", value: "Australian Shepherd"},
  {key: "Australian Terrier", text: "Australian Terrier", value: "Australian Terrier"},
  {key: "Basenji", text: "Basenji", value: "Basenji"},
  {key: "Basset Hound", text: "Basset Hound", value: "Basset Hound"},
  {key: "Beagle", text: "Beagle", value: "Beagle"},
  {key: "Bearded Collie", text: "Bearded Collie", value: "Bearded Collie"},
  {key: "Beauceron", text: "Beauceron", value: "Beauceron"},
  {key: "Bedlington Terrier", text: "Bedlington Terrier", value: "Bedlington Terrier"},
  {key: "Belgian Malinois", text: "Belgian Malinois", value: "Belgian Malinois"},
  {key: "Belgian Sheepdog", text: "Belgian Sheepdog", value: "Belgian Sheepdog"},
  {key: "Belgian Tervuren", text: "Belgian Tervuren", value: "Belgian Tervuren"},
  {key: "Bernese Mountain Dog", text: "Bernese Mountain Dog", value: "Bernese Mountain Dog"},
  {key: "Bichon Frise", text: "Bichon Frise", value: "Bichon Frise"},
  {key: "Black And Tan Coonhound", text: "Black And Tan Coonhound", value: "Black And Tan Coonhound"},
  {key: "Black Russian Terrier", text: "Black Russian Terrier", value: "Black Russian Terrier"},
  {key: "Bloodhound", text: "Bloodhound", value: "Bloodhound"},
  {key: "Border Collie", text: "Border Collie", value: "Border Collie"},
  {key: "Border Terrier", text: "Border Terrier", value: "Border Terrier"},
  {key: "Borzoi", text: "Borzoi", value: "Borzoi"},
  {key: "Boston Terrier", text: "Boston Terrier", value: "Boston Terrier"},
  {key: "Bouvier Des Flandres", text: "Bouvier Des Flandres", value: "Bouvier Des Flandres"},
  {key: "Boxer", text: "Boxer", value: "Boxer"},
  {key: "Briard", text: "Briard", value: "Briard"},
  {key: "Brittany", text: "Brittany", value: "Brittany"},
  {key: "Brussels Griffon", text: "Brussels Griffon", value: "Brussels Griffon"},
  {key: "Bull Dog", text: "Bull Dog", value: "Bull Dog"},
  {key: "Bull Terrier", text: "Bull Terrier", value: "Bull Terrier"},
  {key: "Bullmastiff", text: "Bullmastiff", value: "Bullmastiff"},
  {key: "Cairn Terrier", text: "Cairn Terrier", value: "Cairn Terrier"},
  {key: "Canaan Dog", text: "Canaan Dog", value: "Canaan Dog"},
  {key: "Cardigan Welsh Corgi", text: "Cardigan Welsh Corgi", value: "Cardigan Welsh Corgi"},
  {key: "Cavalier King Charles Spaniel", text: "Cavalier King Charles Spaniel", value: "Cavalier King Charles Spaniel"},
  {key: "Chesapeake Bay Retriever", text: "Chesapeake Bay Retriever", value: "Chesapeake Bay Retriever"},
  {key: "Chihuahua", text: "Chihuahua", value: "Chihuahua"},
  {key: "Chinese Crested", text: "Chinese Crested", value: "Chinese Crested"},
  {key: "Chinese Shar Pei", text: "Chinese Shar Pei", value: "Chinese Shar Pei"},
  {key: "Chow Chow", text: "Chow Chow", value: "Chow Chow"},
  {key: "Clumber Spaniel", text: "Clumber Spaniel", value: "Clumber Spaniel"},
  {key: "Cocker Spaniel-American", text: "Cocker Spaniel-American", value: "Cocker Spaniel-American"},
  {key: "Cocker Spaniel-English", text: "Cocker Spaniel-English", value: "Cocker Spaniel-English"},
  {key: "Collie", text: "Collie", value: "Collie"},
  {key: "Coton de Tulear", text: "Coton de Tulear", value: "Coton de Tulear"},
  {key: "Curly Coated Retriever", text: "Curly Coated Retriever", value: "Curly Coated Retriever"},
  {key: "Dachshund", text: "Dachshund", value: "Dachshund"},
  {key: "Dalmatian", text: "Dalmatian", value: "Dalmatian"},
  {key: "Dandie Dinmont Terrier", text: "Dandie Dinmont Terrier", value: "Dandie Dinmont Terrier"},
  {key: "Doberman Pinscher", text: "Doberman Pinscher", value: "Doberman Pinscher"},
  {key: "English Foxhound", text: "English Foxhound", value: "English Foxhound"},
  {key: "English Setter", text: "English Setter", value: "English Setter"},
  {key: "English Springer Spaniel", text: "English Springer Spaniel", value: "English Springer Spaniel"},
  {key: "English Toy Spaniel", text: "English Toy Spaniel", value: "English Toy Spaniel"},
  {key: "Field Spaniel", text: "Field Spaniel", value: "Field Spaniel"},
  {key: "Finnish Spitz", text: "Finnish Spitz", value: "Finnish Spitz"},
  {key: "Flat Coated Retriever", text: "Flat Coated Retriever", value: "Flat Coated Retriever"},
  {key: "Fox Terrier", text: "Fox Terrier", value: "Fox Terrier"},
  {key: "French Bulldog", text: "French Bulldog", value: "French Bulldog"},
  {key: "German Pinscher", text: "German Pinscher", value: "German Pinscher"},
  {key: "German Shepherd Dog", text: "German Shepherd Dog", value: "German Shepherd Dog"},
  {key: "German Shorthaired Pointer", text: "German Shorthaired Pointer", value: "German Shorthaired Pointer"},
  {key: "German Wirehaired Pointer", text: "German Wirehaired Pointer", value: "German Wirehaired Pointer"},
  {key: "Giant Schnauzer", text: "Giant Schnauzer", value: "Giant Schnauzer"},
  {key: "Glen Imaal Terrier", text: "Glen Imaal Terrier", value: "Glen Imaal Terrier"},
  {key: "Golden Retriever", text: "Golden Retriever", value: "Golden Retriever"},
  {key: "Gordon Setter", text: "Gordon Setter", value: "Gordon Setter"},
  {key: "Great Dane", text: "Great Dane", value: "Great Dane"},
  {key: "Great Pyrenees", text: "Great Pyrenees", value: "Great Pyrenees"},
  {key: "Great Swiss Mountain Dog", text: "Great Swiss Mountain Dog", value: "Great Swiss Mountain Dog"},
  {key: "Greyhound", text: "Greyhound", value: "Greyhound"},
  {key: "Harrier", text: "Harrier", value: "Harrier"},
  {key: "Ibizan Hound", text: "Ibizan Hound", value: "Ibizan Hound"},
  {key: "Irish Setter", text: "Irish Setter", value: "Irish Setter"},
  {key: "Irish Terrier", text: "Irish Terrier", value: "Irish Terrier"},
  {key: "Irish Water Spaniel", text: "Irish Water Spaniel", value: "Irish Water Spaniel"},
  {key: "Irish Wolfhound", text: "Irish Wolfhound", value: "Irish Wolfhound"},
  {key: "Italian Greyhound", text: "Italian Greyhound", value: "Italian Greyhound"},
  {key: "Japanese Chin", text: "Japanese Chin", value: "Japanese Chin"},
  {key: "Keeshond", text: "Keeshond", value: "Keeshond"},
  {key: "Kerry Blue Terrier", text: "Kerry Blue Terrier", value: "Kerry Blue Terrier"},
  {key: "Komondor", text: "Komondor", value: "Komondor"},
  {key: "Kuvasz", text: "Kuvasz", value: "Kuvasz"},
  {key: "Labrador Retriever", text: "Labrador Retriever", value: "Labrador Retriever"},
  {key: "Lakeland Terrier", text: "Lakeland Terrier", value: "Lakeland Terrier"},
  {key: "Maltese", text: "Maltese", value: "Maltese"},
  {key: "Manchester Terrier (Standard)", text: "Manchester Terrier (Standard)", value: "Manchester Terrier (Standard)"},
  {key: "Manchester Terrier (Toy)", text: "Manchester Terrier (Toy)", value: "Manchester Terrier (Toy)"},
  {key: "Mastiff", text: "Mastiff", value: "Mastiff"},
  {key: "Neopolitan Mastiff", text: "Neopolitan Mastiff", value: "Neopolitan Mastiff"},
  {key: "Newfoundland", text: "Newfoundland", value: "Newfoundland"},
  {key: "Norwegian Elkhound", text: "Norwegian Elkhound", value: "Norwegian Elkhound"},
  {key: "Nova Scotia Duck Tolling Retriever", text: "Nova Scotia Duck Tolling Retriever", value: "Nova Scotia Duck Tolling Retriever"},
  {key: "Old English Sheepdog", text: "Old English Sheepdog", value: "Old English Sheepdog"},
  {key: "Otter Hound", text: "Otter Hound", value: "Otter Hound"},
  {key: "Papillon", text: "Papillon", value: "Papillon"},
  {key: "Petit Basset Griffon Vendeen", text: "Petit Basset Griffon Vendeen", value: "Petit Basset Griffon Vendeen"},
  {key: "Pharaoh Hound", text: "Pharaoh Hound", value: "Pharaoh Hound"},
  {key: "Plott Hound", text: "Plott Hound", value: "Plott Hound"},
  {key: "Pointer", text: "Pointer", value: "Pointer"},
  {key: "Polish Lowland Sheepdog", text: "Polish Lowland Sheepdog", value: "Polish Lowland Sheepdog"},
  {key: "Pomeranian", text: "Pomeranian", value: "Pomeranian"},
  {key: "Poodle Miniature", text: "Poodle Miniature", value: "Poodle Miniature"},
  {key: "Poodle Standard", text: "Poodle Standard", value: "Poodle Standard"},
  {key: "Poodle Toy", text: "Poodle Toy", value: "Poodle Toy"},
  {key: "Portuguese Water Dog", text: "Portuguese Water Dog", value: "Portuguese Water Dog"},
  {key: "Pug", text: "Pug", value: "Pug"},
  {key: "Puli", text: "Puli", value: "Puli"},
  {key: "Redbone Coonhound", text: "Redbone Coonhound", value: "Redbone Coonhound"},
  {key: "Rhodesian Ridgeback", text: "Rhodesian Ridgeback", value: "Rhodesian Ridgeback"},
  {key: "Rottweiler", text: "Rottweiler", value: "Rottweiler"},
  {key: "Saint Bernard", text: "Saint Bernard", value: "Saint Bernard"},
  {key: "Saluki", text: "Saluki", value: "Saluki"},
  {key: "Samoyed", text: "Samoyed", value: "Samoyed"},
  {key: "Schipperke", text: "Schipperke", value: "Schipperke"},
  {key: "Scottish Deerhound", text: "Scottish Deerhound", value: "Scottish Deerhound"},
  {key: "Scottish Terrier", text: "Scottish Terrier", value: "Scottish Terrier"},
  {key: "Sealyham Terrier", text: "Sealyham Terrier", value: "Sealyham Terrier"},
  {key: "Shetland Sheepdog", text: "Shetland Sheepdog", value: "Shetland Sheepdog"},
  {key: "Shiba Inu", text: "Shiba Inu", value: "Shiba Inu"},
  {key: "Shih Tzu", text: "Shih Tzu", value: "Shih Tzu"},
  {key: "Siberian Husky", text: "Siberian Husky", value: "Siberian Husky"},
  {key: "Silky Terrier", text: "Silky Terrier", value: "Silky Terrier"},
  {key: "Skye Terrier", text: "Skye Terrier", value: "Skye Terrier"},
  {key: "Soft-Coated Wheaten Terrier", text: "Soft-Coated Wheaten Terrier", value: "Soft-Coated Wheaten Terrier"},
  {key: "Spinone Italiano", text: "Spinone Italiano", value: "Spinone Italiano"},
  {key: "Staffordshire Bull Terrier", text: "Staffordshire Bull Terrier", value: "Staffordshire Bull Terrier"},
  {key: "Standard Schnauzer", text: "Standard Schnauzer", value: "Standard Schnauzer"},
  {key: "Sussex Spaniel", text: "Sussex Spaniel", value: "Sussex Spaniel"},
  {key: "Tibetan Mastiff", text: "Tibetan Mastiff", value: "Tibetan Mastiff"},
  {key: "Tibetan Spaniel", text: "Tibetan Spaniel", value: "Tibetan Spaniel"},
  {key: "Tibetan Terrier", text: "Tibetan Terrier", value: "Tibetan Terrier"},
  {key: "Toy Fox Terrier", text: "Toy Fox Terrier", value: "Toy Fox Terrier"},
  {key: "Vizsla", text: "Vizsla", value: "Vizsla"},
  {key: "Weimaraner", text: "Weimaraner", value: "Weimaraner"},
  {key: "Welsh Springer Spaniel", text: "Welsh Springer Spaniel", value: "Welsh Springer Spaniel"},
  {key: "Welsh Terrier", text: "Welsh Terrier", value: "Welsh Terrier"},
  {key: "West Highland White Terrier", text: "West Highland White Terrier", value: "West Highland White Terrier"},
  {key: "Whippet", text: "Whippet", value: "Whippet"},
  {key: "Wirehaired Pointing Griffon", text: "Wirehaired Pointing Griffon", value: "Wirehaired Pointing Griffon"},
  {key: "Yorkshire Terrier", text: "Yorkshire Terrier", value: "Yorkshire Terrier"},
]